const FoodImages = {
    barbeque1: require('../assets/images/foods/barbeque-1.jpeg'),
    barbeque2: require('../assets/images/foods/barbeque-2.jpeg'),
    barbeque3: require('../assets/images/foods/barbeque-3.jpeg'),
    burgers1: require('../assets/images/foods/burgers-1.jpeg'),
    burgers2: require('../assets/images/foods/burgers-2.jpeg'),
    burgers3: require('../assets/images/foods/burgers-3.jpeg'),
    cajunCreole1: require('../assets/images/foods/cajun_creole-1.jpeg'),
    chinese1: require('../assets/images/foods/chinese-1.jpeg'),
    chinese2: require('../assets/images/foods/chinese-2.jpeg'),
    chinese3: require('../assets/images/foods/chinese-3.jpeg'),
    deli1: require('../assets/images/foods/deli-1.jpeg'),
    deli2: require('../assets/images/foods/deli-2.jpeg'),
    deli3: require('../assets/images/foods/deli-3.jpeg'),
    french1: require('../assets/images/foods/french-1.jpeg'),
    indian1: require('../assets/images/foods/indian-1.jpeg'),
    indian2: require('../assets/images/foods/indian-2.jpeg'),
    indian3: require('../assets/images/foods/indian-3.jpeg'),
    italian1: require('../assets/images/foods/italian-1.jpeg'),
    italian2: require('../assets/images/foods/italian-2.jpeg'),
    italian3: require('../assets/images/foods/italian-3.jpeg'),
    mexican1: require('../assets/images/foods/mexican-1.jpeg'),
    pizza1: require('../assets/images/foods/pizza-1.jpeg'),
    pizza2: require('../assets/images/foods/pizza-2.jpeg'),
    pizza3: require('../assets/images/foods/pizza-3.jpeg'),
    steakhouse1: require('../assets/images/foods/steakhouse-1.jpeg'),
    steakhouse2: require('../assets/images/foods/steakhouse-2.jpeg'),
    steakhouse3: require('../assets/images/foods/steakhouse-3.jpeg'),
    sushi1: require('../assets/images/foods/sushi-1.jpeg'),
    sushi2: require('../assets/images/foods/sushi-2.jpeg'),
    sushi3: require('../assets/images/foods/sushi-3.jpeg'),
}

export default FoodImages;